### ISSUE TITLE
[Bug]: release-to-candidate store token File contains no section headers

### ISSUE THREAD

**Issue by jardon** [snapcrafters/ci#48] opened 2024-11-18 17:57 UTC
### What happened?

my snap fails to authenticate with the snap store in the release-to-candidate ci workflow.  ive tested the token locally by exporting it and running `snapcraft whoami`.

### What should have happened?

the workflow should authenticate with the snapstore with the given token

### Output of `snap info $snap_name`

```shell
NA
```

### Output of `snap connections $snap_name`

```shell
NA
```

### Output of `snap version`

```shell
NA
```

### Relevant log output

[actions log](https://github.com/jardon/qt-framework-sdk-snap/actions/runs/11897905866/job/33153201782)

**Comment by jardon** [comment] 2024-11-18 17:58
I'm sure i did something wrong, but its not documented from what i could find.  I followed the token generation instructions [here](https://snapcraft.io/docs/snapcraft-authentication#heading--export).

**Comment by jardon** [comment] 2024-11-18 18:01
its worth noting that both the token and action are using `latest/stable` which is `8.4.4` at this time.

**Comment by mr-cal** [comment] 2024-11-18 21:07
From the log, I see:
```
 File contains no section headers.
file: '/home/runner/.local/share/snapcraft/launchpad-credentials', line: 1
'***\n'
```

The problem is due to how Github handles new lines in secrets.  You need to replace all new lines in the Launchpad secret token with `\n`.  

Documenting this has been [brought up](https://matrix.to/#/!cniCqhKpzVvOBMHAVt:matrix.org/$8WJxQbEixugw7Td5mvjB8DxvebrhfLQM8ZnDkcNvzXY?via=matrix.org&via=ubuntu.com&via=xentonix.net) by the snapcrafters before.  I was planning to [document this for Snapcraft](https://github.com/canonical/craft-application/issues/429) but the effort was dropped when we decided not to support remote-build in CI.

**Comment by mr-cal** [comment] 2024-11-18 21:31
I see it is documented here: https://github.com/snapcrafters/.github/wiki/Permissions-and-Secrets

I updated that page with the caveat about newlines and the new credential location for Snapcraft>=8.2.0

**Comment by jardon** [comment] 2024-11-18 23:07
that actually ended up not being my issue, but it did help me figure out what was wrong.  what would be helpful is updating the documentation to link to some of these online resources.  theres nothing in the readme that appropriately describes the secrets or directs the user toward the docs. 

so in this case, i went down the wrong path and supplied something other than what it was looking for.

**Comment by jnsgruk** [comment] 2024-11-19 08:55
Glad you got it figured out, I'll close this out for now!

**Closed** 2024-11-19 08:55 UTC
Labels: bug
